version: '3'

services:

  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    networks:
      - devops-network
    container_name: postgres
    environment:
      POSTGRES_DB: "petz"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "petz"
    volumes:
      - ~/Petz_DB/data:/var/lib/postgresql/data:rw

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    networks:
      - devops-network
    ports:
      - 8810:8080
    depends_on:
      - postgres

networks:
  devops-network: