version: '3'

services:

  mysql:
    image: mysql
    restart: always
    networks:
      - devops-network
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=petz
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - .docker-volume/mysql-data/db:/var/lib/mysql:rw
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    networks:
      - devops-network
    ports:
      - 8810:8080
    depends_on:
      - mysql

networks:
  devops-network: