server:
  port: ${SERVER_PORT}

spring:
  profiles:
    active: local
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  messages:
    basename: messages
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true