server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/petz?createDatabaseIfNotExist=true&serverTimeZone=UTC"
    username: admin
    password: admin
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3
      idle-timeout: 10000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: false
      javax:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: src/main/resources/ddl.sql
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db/migration, classpath:db/testdata