server:
  port: 8080

spring:
  datasource:
    driver-class-datasetName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/petz"
    username: postgres
    password: petz
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3
      idle-timeout: 10000
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
      javax:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: src/main/resources/ddl.sql
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db/migration, classpath:db/testdata